name: GitHub Actions Build
on: [ push, workflow_dispatch ]
jobs:
  Build-dist:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: pyinstaller main.spec
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: |
